# report_generator.py

# NOT IN USE

import asyncio
import os
import logging
from dotenv import load_dotenv
from openai import AsyncOpenAI

logger = logging.getLogger(__name__)

load_dotenv()
client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))

async def generate_markdown_report(text: str) -> str:
    """
    Takes markdown generated by crawl4ai and converts it into a structured
    research-style Markdown report using an LLM.
    """

    if not text or len(text.strip()) == 0:
        return "# Empty Document\n\nNo content was extracted."

    prompt = f"""
You are a professional research analyst.

Transform the following markdown content into a clean, well-structured
Markdown research report.

Requirements:
- Add a clear title (H1)
- Add logical section headings (H2/H3)
- Summarize long sections
- Remove navigation/footer noise
- Use bullet points where appropriate
- Keep it concise but informative
- Preserve important technical details

Raw Content:
{text[:15000]}
"""

    response = await client.responses.create(
        model="gpt-4.1-mini",
        input=prompt,
        temperature=0.3,
        max_output_tokens=2000,
    )

    markdown = response.output[0].content[0].text
    
    logger.info(f"LLM generated markdown response.")

    return markdown.strip()